/*
DECLARE @database varchar(20) = 'master'
DECLARE @schema varchar(20) = 'dbo'
DECLARE @table varchar(25) = 'MSreplication_options'
*/
SELECT 

    c.COLUMN_NAME, 
    c.IS_NULLABLE, 
    c.DATA_TYPE, 
    c.CHARACTER_MAXIMUM_LENGTH, 
    tc.CONSTRAINT_TYPE, 
    cc.CONSTRAINT_NAME

FROM /*DATABASE_NAME.*/INFORMATION_SCHEMA.COLUMNS c 

LEFT JOIN /*DATABASE_NAME.*/INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE cc
ON 
    cc.TABLE_CATALOG = c.TABLE_CATALOG AND 
    cc.TABLE_SCHEMA = c.TABLE_SCHEMA AND 
    cc.TABLE_NAME = c.TABLE_NAME AND 
    cc.COLUMN_NAME = c.COLUMN_NAME

LEFT JOIN /*DATABASE_NAME.*/INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
ON 
    tc.TABLE_CATALOG = c.TABLE_CATALOG AND 
    tc.TABLE_SCHEMA = c.TABLE_SCHEMA AND    
    tc.TABLE_NAME = c.TABLE_NAME AND 
    tc.CONSTRAINT_NAME = cc.CONSTRAINT_NAME

WHERE 
    c.TABLE_CATALOG = @database AND
    c.TABLE_SCHEMA = @schema AND
    c.TABLE_NAME = @table 

ORDER BY c.ORDINAL_POSITION