USE [master]

SELECT 
    tb.TABLE_SCHEMA, 
    tb.TABLE_NAME, 
    tb.TABLE_TYPE,
    cl.COLUMN_NAME, 
    cl.IS_NULLABLE, 
    cl.DATA_TYPE, 
    cl.CHARACTER_MAXIMUM_LENGTH, 
    tc.CONSTRAINT_TYPE, 
    cc.CONSTRAINT_NAME

FROM INFORMATION_SCHEMA.COLUMNS cl 

INNER JOIN INFORMATION_SCHEMA.TABLES tb 
ON  
    tb.TABLE_CATALOG = cl.TABLE_CATALOG AND 
    tb.TABLE_SCHEMA = cl.TABLE_SCHEMA AND 
    tb.TABLE_NAME = cl.TABLE_NAME

LEFT JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE cc
ON 
    cc.TABLE_CATALOG = cl.TABLE_CATALOG AND 
    cc.TABLE_SCHEMA = cl.TABLE_SCHEMA AND 
    cc.TABLE_NAME = cl.TABLE_NAME AND 
    cc.COLUMN_NAME = cl.COLUMN_NAME

LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
ON 
    tc.TABLE_CATALOG = cl.TABLE_CATALOG AND 
    tc.TABLE_SCHEMA = cl.TABLE_SCHEMA AND 
    tc.TABLE_NAME = cl.TABLE_NAME AND 
    tc.CONSTRAINT_NAME = cc.CONSTRAINT_NAME

ORDER BY 1, 2, cl.ORDINAL_POSITION