version: '3'

networks:
    localhost:
        driver: bridge

services:

    mssql:
        image: mcr.microsoft.com/mssql/server:2017-GA-ubuntu
        container_name: mssql
        networks:
            - localhost
        ports:
            - "1433:1433"
        environment:
            - "ACCEPT_EULA=Y"
            - "SA_PASSWORD=Passw0rd!"

    mysql:
        image: mysql:latest
        container_name: mysql
        networks:
            - localhost 
        ports:
            - "3306:3306"
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: "Passw0rd!"
